-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
vim.g.use_nerd_icons = false
if vim.fn.has("mac") == 1 or vim.g.use_nerd_icons then
	-- elseif vim.fn.has "mac" == 1 then
	return {
		kind = {
			Text = "",
			Method = "",
			Function = "",
			Constructor = "",
			Field = "ﰠ",
			Variable = "",
			Class = "ﴯ",
			Interface = "",
			Module = "",
			Property = "ﰠ",
			Unit = "塞",
			Value = "",
			Enum = "",
			Keyword = "",
			Snippet = "",
			Color = "",
			File = "",
			Refeence = "",
			Folder = "",
			EnumMember = "",
			Constant = "",
			Struct = "פּ",
			Event = "",
			Operator = "",
			TypeParameter = "",
		},
		type = {
			Array = "",
			Number = "",
			String = "",
			Boolean = "蘒",
			Object = "",
		},
		documents = {
			File = "",
			Files = "",
			Folder = "",
			OpenFolder = "",
		},
		git = {
			Add = "",
			Mod = "",
			Remove = "",
			Ignore = "",
			Rename = "",
			Diff = "",
			Repo = "",
		},
		ui = {
			ArrowClosed = "",
			ArrowOpen = "",
			Lock = "",
			Circle = "",
			BigCircle = "",
			BigUnfilledCircle = "",
			Close = "",
			NewFile = "",
			Search = "",
			Lightbulb = "",
			Project = "",
			Dashboard = "",
			History = "",
			Comment = "",
			Bug = "",
			Code = "",
			Telescope = "",
			Gear = "",
			Package = "",
			List = "",
			SignIn = "",
			SignOut = "",
			Check = "",
			Fire = "",
			Note = "",
			BookMark = "",
			Pencil = "",
			-- ChevronRight = "",
			ChevronRight = ">",
			Table = "",
			Calendar = "",
			CloudDownload = "",
		},
		diagnostics = {
			Error = "",
			Warning = "",
			Information = "",
			Question = "",
			Hint = "",
		},
		misc = {
			Robot = "ﮧ ",
			Squirrel = " ",
			Tag = " ",
			Watch = " ",
		},
	}
else
	--   פּ ﯟ   蘒練 some other good icons
	return {
		kind = {
			Text = "",
			Method = "",
			Function = "",
			Constructor = "",
			Field = "ﰠ",
			Variable = "",
			Class = "ﴯ",
			Interface = "",
			Module = "",
			Property = "ﰠ",
			Unit = "塞",
			Value = "",
			Enum = "",
			Keyword = "",
			Snippet = "",
			Color = "",
			File = "",
			Refeence = "",
			Folder = "",
			EnumMember = "",
			Constant = "",
			Struct = "פּ",
			Event = "",
			Operator = "",
			TypeParameter = "",
		},
		type = {
			Array = " ",
			Number = " ",
			String = " ",
			Boolean = " ",
			Object = " ",
		},
		documents = {
			File = " ",
			Files = " ",
			Folder = " ",
			OpenFolder = " ",
		},
		git = {
			Add = " ",
			Mod = " ",
			Remove = " ",
			Ignore = " ",
			Rename = " ",
			Diff = " ",
			Repo = " ",
		},
		ui = {
			ArrowClosed = "",
			ArrowOpen = "",
			Lock = " ",
			Circle = " ",
			BigCircle = " ",
			BigUnfilledCircle = " ",
			Close = " ",
			NewFile = " ",
			Search = " ",
			Lightbulb = " ",
			Project = " ",
			Dashboard = " ",
			History = " ",
			Comment = " ",
			Bug = " ",
			Code = " ",
			Telescope = " ",
			Gear = " ",
			Package = " ",
			List = " ",
			SignIn = " ",
			SignOut = " ",
			NoteBook = " ",
			Check = " ",
			Fire = " ",
			Note = " ",
			BookMark = " ",
			Pencil = " ",
			ChevronRight = "",
			Table = " ",
			Calendar = " ",
			CloudDownload = " ",
		},
		diagnostics = {
			Error = "",
			Warning = "",
			Information = "",
			Question = "",
			Hint = "",
		},
		misc = {
			Robot = " ",
			Squirrel = " ",
			Tag = " ",
			Watch = " ",
		},
	}
end
